### PR TITLE
Added C# native version of InputController

### PR DESCRIPTION
**Pull request by CBurlison**
The C# version has events that can be subscribed to via code along with still emitting signals that can be used via the UI or GDScript that is used alongside it.

### CODE REVIEW

**Comment by sscovil** [comment]
Hey @CBurlison, Thanks for contributing!

Can you share your rationale for making this change? It's not clear to me why this would be necessary, and why literally every line of code—including the `README.md` and image files—needed to be replicated. (**EDIT:** I see it now...you created a new directory called `InputController` alongside `input_controller`. Still not sure why this is necessary though.)

Candidly, as a solo developer who doesn't normally use C#, I find the idea of maintaining this a bit daunting... 😅

**Comment by CBurlison** [comment]
Sure. My main reasoning for this is full control while writing in C#. Unfortunately without Godot's translation layer, working with gd scripts directly isn't really practical. The full port is more or less to allow for the same level of control in code like the GDscript version gets. All that said it was more or less my intention to maintain this in the fork I had made simply because this seems like a great tool, if you would prefer to keep them separate that is A-OK. 

I am following your work here so if you do decide to make any changes to it I should be able to keep parity without any issue.

**Comment by sscovil** [comment]
Okay, makes sense. Let's keep them separate for now, just so I don't have to worry about release management and issues that are specific to the C# version. 

And thanks for taking the initiative! I'm glad to see folks finding this plugin useful. 

Also, just FYI: I'll be adding support for local multi-player next. Right now, the InputController doesn't discern between different devices, so more than one joypad connected at the same time would cause chaos. :-)

**Comment by CBurlison** [comment]
Sounds good!

**Pull request closed without merging**
